apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: aibrix-custom-proxy-config
  namespace: aibrix-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                service.beta.kubernetes.io/volcengine-loadbalancer-address-type: "PRIVATE"
            spec:
              ipFamilies:
                - IPv4
                - IPv6
              ipFamilyPolicy: PreferDualStack
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            pod:
              annotations:
                vci.vke.volcengine.com/pod-ip-family: dualstack
            container:
              name: envoy
              image: aibrix-container-registry-cn-beijing.cr.volces.com/envoyproxy/envoy:distroless-v1.31.0
              resources:
                requests:
                  cpu: 2
                  memory: 8Gi
                limits:
                  cpu: 2
                  memory: 8Gi